### PR TITLE
Phala Darkpool Exchange

### PR DESCRIPTION
**Pull request by ndkazu**
Bounty request for the development of a Phala Darkpool Exchange

### CODE REVIEW

**Comment by shelvenzhou** [comment]
I personally like this proposal and I recommend providing some extra information to make this more understandable by the Council and the Phala team:

- Compared with the Darkpool Exchange submitted in the hackathon, what are the major differences and innovations of this project?
- Some design details are needed, they are not a must in the application, but clarifying these details can greatly increase our confidence in this project, and let the Phala team understand and make the necessary changes to satisfy your requirements
    - About how users interact with the exchange
         - For centralized exchanges, users directly interact with centralized servers; for previous decentralized solutions, users interact with the chain. While in Phala, users send Commands to the chain and send Queries to the workers, so it's important to list the application scenarios where users send Commands or Queries and determine the requirements on the workers (e.g., their network quality, e.t.c.);
    - Does the contract need to manage the assets or just use existing APIs to do this?
    - A more detailed design about how users append and withdraw their biddings (with Commands or Queries?), I suggest some process flow diagrams;

**Comment by h4x3rotab** [comment]
Please also add a link to this PR (or the file URL after merged) in the [bounty page](https://khala.subsquare.io/treasury/bounty/5).

**Comment by ndkazu** [comment]
> I personally like this proposal and I recommend providing some extra information to make this more understandable by the Council and the Phala team:
> 
> * Compared with the Darkpool Exchange submitted in the hackathon, what are the major differences and innovations of this project?
> * Some design details are needed, they are not a must in the application, but clarifying these details can greatly increase our confidence in this project, and let the Phala team understand and make the necessary changes to satisfy your requirements
>   
>   * About how users interact with the exchange
>     
>     * For centralized exchanges, users directly interact with centralized servers; for previous decentralized solutions, users interact with the chain. While in Phala, users send Commands to the chain and send Queries to the workers, so it's important to list the application scenarios where users send Commands or Queries and determine the requirements on the workers (e.g., their network quality, e.t.c.);
>   * Does the contract need to manage the assets or just use existing APIs to do this?
>   * A more detailed design about how users append and withdraw their biddings (with Commands or Queries?), I suggest some process flow diagrams;

The Proposal has been updated, in order to fulfill the above requirements and suggestions as much as possible.
Further feedback is always welcomed

**Comment by ndkazu** [comment]
> Please also add a link to this PR (or the file URL after merged) in the [bounty page](https://khala.subsquare.io/treasury/bounty/5).

A comment containing the PR link, and explaining that a new/corrected on-chain submission is needed, was added.

**Comment by ndkazu** [comment]
- Allocation breakdown, and collator allocation have been added
- Milestones have been updated

**Pull request closed without merging**
