### PR TITLE
Phala Router (PRouter) and Off Chain Latency Graph Optimization

### PR DESCRIPTION
**Pull request by Soptq**

### CODE REVIEW

**Comment by shelvenzhou** [comment]
Milestone 1 Submission: https://github.com/Phala-Network/phala-blockchain/pull/588

**Comment by h4x3rotab** [comment]
We don't have the amount of each milestone described in the proposal

**Comment by Soptq** [comment]
45NAoz4deiVVYbnAtGXTHQua4JCTJEErMa7N5SxK1jAw4Geo

**Comment by h4x3rotab** [comment]
Congratulations! The Milestone 2 is accepted.

The amount of the M2 bounty is $5000. The current rate of PHA is 0.1231 USD (from CoinMarketCap). We've paid to your Khala wallet `40650` PHA  in extrinsics [1](https://khala.subscan.io/extrinsic/2003661-15) and [2](https://khala.subscan.io/extrinsic/2003674-10).

**Pull request merged**
